Repository CA-G12/Team-8-E-commerce, pull requests merged in 2022-07, with the labels that each got.

#26 Create Project Structure.
  Cart/cart.css
  Cart/cart.html
  Cart/cart.js
  Cart/logic.js
  Customer/customer.css
  Customer/customer.html
  Customer/customer.js
  Customer/logic.js
  LandingPage/style.css
  Seller/logic.js
  Seller/seller.css
  Seller/seller.html
  Seller/seller.js
  SharedFunctions/shared-functions.js
  __tests__/pure-functions.test.js
  index.html
  package-lock.json
  package.json
Labels: awaiting-review

#27 Created the readme file.
  README.md
Labels: awaiting-review

#28 Added the html structure for the seller page.
  Seller/seller.html
Labels: approved

#29 Create Landing Page HTML Structure For Create Landing Page
  index.html
Labels: approved

#30 Create Landing Page Styles For
  LandingPage/style.css
  index.html
Labels: approved

#31 Styled the seller page.
  Seller/seller.css
  Seller/seller.html
Labels: done

#33 Added the products array of objects
  Seller/seller.js
Labels: approved

#35 13 customer home style
  Customer/customer.css
  Customer/customer.html
Labels: awaiting-review

#34 set the layout of customer home page
  Customer/customer.html
Labels: awaiting-review

#38 Delete Product Function.
  Seller/logic.js
  Seller/seller.js
  __tests__/pure-functions.test.js
  package.json
Labels: approved

#36 Create HTML cart page structure
  Cart/cart.html
Labels: approved

#39 Added the seller's new product form.
  Seller/seller.html
Labels: approved

#40 Styled the form element.
  Seller/seller.css
  Seller/seller.html
Labels: awaiting-review

#42 Close form function.
  Seller/seller.css
  Seller/seller.html
  Seller/seller.js
Labels: awaiting-review

#44 add data-id attribute to product section in html, addToCafunction, te…
  Customer/customer.html
  Customer/customer.js
  Customer/logic.js
  __tests__/pure-functions.test.js
  package.json
Labels: awaiting-review

#45 Add new product button in html, css, and js.
  Seller/seller.css
  Seller/seller.html
  Seller/seller.js
Labels: awaiting-review

#47 add the cart folder relats #8
  Cart/cart.css
  Cart/cart.html
  Cart/cart.js
  Cart/logic.js
Labels: awaiting-review

#46 add total price function and test
  Customer/logic.js
  __tests__/pure-functions.test.js
Labels: done

#52 taking data from local storage, add to cart, sorting by price functio…
  Customer/customer.html
  Customer/customer.js
  Customer/logic.js
  __tests__/pure-functions.test.js
Labels: approved

#51 fixing the bugs.
  Seller/logic.js
  Seller/seller.css
  Seller/seller.js
  __tests__/pure-functions.test.js
Labels: awaiting-review
